// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_cinnagaran",\
"rri_weapon_cinnagaran_bcsewpn"

#define UNIT_LIST \
"rri_weapon_cinnagaran_GH",\
"rri_weapon_cinnagaran_bcsewpn_GH"
