// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_cinnagaran,rri_mag_cinnagaran,"[SOB] Cinnagaran Carbine");
MACRO_GH_WEAPON(rri_weapon_cinnagaran_bcsewpn,rri_mag_cinnagaran,"[SOB] Cinnagaran Carbine");
