// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_zh_short",\
"rri_weapon_zh_short_foregrip",\
"rri_weapon_zh_long",\
"rri_weapon_zh_long_foregrip",\
"rri_weapon_zh_long_GL",\
"rri_weapon_zh_long_GL_foregrip",\
"rri_weapon_zh_short_bcsewpn",\
"rri_weapon_zh_long_bcsewpn",\
"rri_weapon_zh_long_GL_bcsewpn",\
"rri_weapons_zh73_zh_torch",\
"rri_weapons_zh73_zh_foregrip",\
"rri_weapons_zh73_zh_suppressor",\
"rri_weapons_zh73_zh_Scope"

#define UNIT_LIST \
"rri_weapon_zh_short_GH",\
"rri_weapon_zh_long_GH",\
"rri_weapon_zh_long_GL_GH",\
"rri_weapon_zh_short_bcsewpn_GH",\
"rri_weapon_zh_long_bcsewpn_GH",\
"rri_weapon_zh_long_GL_bcsewpn_GH",\
"rri_weapons_zh73_zh_torch_GH",\
"rri_weapons_zh73_zh_foregrip_GH",\
"rri_weapons_zh73_zh_suppressor_GH",\
"rri_weapons_zh73_zh_Scope_GH"
