// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_zh_short,rri_mag_zh73,"[SOB] ZH-73 (Assault)");
MACRO_GH_WEAPON(rri_weapon_zh_long,rri_mag_zh73_lr,"[SOB] ZH-73 (Long Rifle)");
MACRO_GH_WEAPON(rri_weapon_zh_long_GL,rri_mag_zh73_lr,"[SOB] ZH-73 GL (Long Rifle)");
MACRO_GH_WEAPON(rri_weapon_zh_short_bcsewpn,rri_mag_zh73,"[SOB] ZH-73 (Assault)");
MACRO_GH_WEAPON(rri_weapon_zh_long_bcsewpn,rri_mag_zh73_lr,"[SOB] ZH-73 (Long Rifle)");
MACRO_GH_WEAPON(rri_weapon_zh_long_GL_bcsewpn,rri_mag_zh73_lr,"[SOB] ZH-73 GL (Long Rifle)");
MACRO_GH_ITEM(rri_weapons_zh73_zh_torch,"[SOB] ZH-73 Torch");
MACRO_GH_ITEM(rri_weapons_zh73_zh_foregrip,"[SOB] ZH-73 Foregrip");
MACRO_GH_ITEM(rri_weapons_zh73_zh_suppressor,"[SOB] ZH Suppressor");
MACRO_GH_ITEM(rri_weapons_zh73_zh_Scope,"[SOB] ZH-73 Scope");
