// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_melee_base",\
"rri_weapon_knife",\
"rri_weapon_hammer",\
"rri_weapon_shovel"

#define UNIT_LIST \
"rri_weapon_knife_GH",\
"rri_weapon_hammer_GH",\
"rri_weapon_shovel_GH"
