// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_knife,WBK_Cybercrystal,"[SOB] Clone Knife");
MACRO_GH_WEAPON(rri_weapon_hammer,WBK_Cybercrystal,"[SOB] Clone Hammer");
MACRO_GH_WEAPON(rri_weapon_shovel,,"[SOB] Clone Shovel");
