// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_DC17S",\
"rri_weapon_DC17Sgf_base",\
"rri_weapon_DC17Sgf"

#define UNIT_LIST \
"rri_weapon_DC17Sgf_GH"
