// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_pcb_base",\
"rri_weapons_pcb99_pcb_scope",\
"rri_weapon_pcb_base_bcsewpn"

#define UNIT_LIST \
"rri_weapon_pcb_base_GH",\
"rri_weapons_pcb99_pcb_scope_GH",\
"rri_weapon_pcb_base_bcsewpn_GH"
