// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_pcb_base,rri_mag_pcb,"[SOB] PCB-99 Railgun");
MACRO_GH_ITEM(rri_weapons_pcb99_pcb_scope,"[SOB] PCB Scope");
MACRO_GH_WEAPON(rri_weapon_pcb_base_bcsewpn,rri_mag_pcb,"[SOB] PCB-99 Railgun");
