// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_btx",\
"rri_weapon_btx_bcsewpn"

#define UNIT_LIST \
"rri_weapon_btx_GH",\
"rri_weapon_btx_bcsewpn_GH"
