// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_btx,rri_mag_BTX,"[SOB] BTX-42 Flamethrower");
MACRO_GH_WEAPON(rri_weapon_btx_bcsewpn,rri_mag_BTX,"[SOB] BTX-42 Flamethrower");
