// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_DC15L",\
"rri_weapon_DC15L_HP",\
"rri_weapon_DC15L_bcsewpn",\
"rri_weapon_DC15L_HP_bcsewpn"

#define UNIT_LIST \
"rri_weapon_DC15L_GH",\
"rri_weapon_DC15L_HP_GH",\
"rri_weapon_DC15L_bcsewpn_GH",\
"rri_weapon_DC15L_HP_bcsewpn_GH"
