// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_DC15L,rri_Mag_DC15L,"[SOB] DC-15L");
MACRO_GH_WEAPON(rri_weapon_DC15L_HP,rri_Mag_DC15L_HP,"[SOB] DC-15L High Power");
MACRO_GH_WEAPON(rri_weapon_DC15L_bcsewpn,rri_Mag_DC15L,"[SOB] DC-15L");
MACRO_GH_WEAPON(rri_weapon_DC15L_HP_bcsewpn,rri_Mag_DC15L_HP,"[SOB] DC-15L High Power");
