// This file is automatically generated by write_aceax_compat.py
// Do not edit this file manually!

class XtdGearModels {
	class CfgWeapons {
		class rri_weapons_dc15l_DC15L {
			label = ACEAX_LABEL_DC15L;
			author = "MokTech Industries";
			options[] = {"power"};

			class power {
				changeingame = 0;
				values[] = {"HighPower", "LowPower"};

				class HighPower { label = "HighPower"; };
				class LowPower { label = "LowPower"; };
			};
		};
	};
};
