// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_DC15A",\
"rri_weapon_DC15A_HP",\
"rri_weapon_DC15A_Wood",\
"rri_weapon_DC15A_HP_Wood",\
"rri_weapon_DC15A_GL",\
"rri_weapon_DC15A_HP_GL",\
"rri_weapon_DC15A_Wood_GL",\
"rri_weapon_DC15A_HP_Wood_GL",\
"rri_weapon_DC19A",\
"rri_weapon_DC15A_bcsewpn",\
"rri_weapon_DC15A_HP_bcsewpn",\
"rri_weapon_DC15A_Wood_bcsewpn",\
"rri_weapon_DC15A_HP_Wood_bcsewpn",\
"rri_weapon_DC15A_GL_bcsewpn",\
"rri_weapon_DC15A_HP_GL_bcsewpn",\
"rri_weapon_DC15A_Wood_GL_bcsewpn",\
"rri_weapon_DC15A_HP_Wood_GL_bcsewpn",\
"rri_weapon_DC19A_bcsewpn"

#define UNIT_LIST \
"rri_weapon_DC15A_GH",\
"rri_weapon_DC15A_HP_GH",\
"rri_weapon_DC15A_Wood_GH",\
"rri_weapon_DC15A_HP_Wood_GH",\
"rri_weapon_DC15A_GL_GH",\
"rri_weapon_DC15A_HP_GL_GH",\
"rri_weapon_DC15A_Wood_GL_GH",\
"rri_weapon_DC15A_HP_Wood_GL_GH",\
"rri_weapon_DC19A_GH",\
"rri_weapon_DC15A_bcsewpn_GH",\
"rri_weapon_DC15A_HP_bcsewpn_GH",\
"rri_weapon_DC15A_Wood_bcsewpn_GH",\
"rri_weapon_DC15A_HP_Wood_bcsewpn_GH",\
"rri_weapon_DC15A_GL_bcsewpn_GH",\
"rri_weapon_DC15A_HP_GL_bcsewpn_GH",\
"rri_weapon_DC15A_Wood_GL_bcsewpn_GH",\
"rri_weapon_DC15A_HP_Wood_GL_bcsewpn_GH",\
"rri_weapon_DC19A_bcsewpn_GH"
