// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_DC15A,rri_mag_DC15A,"[SOB] DC-15A");
MACRO_GH_WEAPON(rri_weapon_DC15A_HP,rri_mag_DC15A,"[SOB] DC-15A (High Power)");
MACRO_GH_WEAPON(rri_weapon_DC15A_Wood,rri_mag_DC15A,"[SOB] DC-15A (Wood Stock)");
MACRO_GH_WEAPON(rri_weapon_DC15A_HP_Wood,rri_mag_DC15A,"[SOB] DC-15A (Wood Stock High Power)");
MACRO_GH_WEAPON(rri_weapon_DC15A_GL,rri_mag_DC15A,"[SOB] DC-15A GL");
MACRO_GH_WEAPON(rri_weapon_DC15A_HP_GL,rri_mag_DC15A,"[SOB] DC-15A GL (High Power)");
MACRO_GH_WEAPON(rri_weapon_DC15A_Wood_GL,rri_mag_DC15A,"[SOB] DC-15A GL (WoodStock)");
MACRO_GH_WEAPON(rri_weapon_DC15A_HP_Wood_GL,rri_mag_DC15A,"[SOB] DC-15A GL (WoodStock High Power)");
MACRO_GH_WEAPON(rri_weapon_DC19A,rri_mag_DC15A,"[SOB] DC-19A");
MACRO_GH_WEAPON(rri_weapon_DC15A_bcsewpn,rri_mag_DC15A,"[SOB] DC-15A");
MACRO_GH_WEAPON(rri_weapon_DC15A_HP_bcsewpn,rri_mag_DC15A,"[SOB] DC-15A (High Power)");
MACRO_GH_WEAPON(rri_weapon_DC15A_Wood_bcsewpn,rri_mag_DC15A,"[SOB] DC-15A (Wood Stock)");
MACRO_GH_WEAPON(rri_weapon_DC15A_HP_Wood_bcsewpn,rri_mag_DC15A,"[SOB] DC-15A (Wood Stock High Power)");
MACRO_GH_WEAPON(rri_weapon_DC15A_GL_bcsewpn,rri_mag_DC15A,"[SOB] DC-15A GL");
MACRO_GH_WEAPON(rri_weapon_DC15A_HP_GL_bcsewpn,rri_mag_DC15A,"[SOB] DC-15A GL (High Power)");
MACRO_GH_WEAPON(rri_weapon_DC15A_Wood_GL_bcsewpn,rri_mag_DC15A,"[SOB] DC-15A GL (WoodStock)");
MACRO_GH_WEAPON(rri_weapon_DC15A_HP_Wood_GL_bcsewpn,rri_mag_DC15A,"[SOB] DC-15A GL (WoodStock High Power)");
MACRO_GH_WEAPON(rri_weapon_DC19A_bcsewpn,rri_mag_DC15A,"[SOB] DC-19A");
