// This file is automatically generated by write_aceax_compat.py
// Do not edit this file manually!

class XtdGearModels {
	class CfgWeapons {
		class rri_weapons_dc15a_DC15A {
			label = ACEAX_LABEL_DC15A;
			author = "MokTech Industries";
			options[] = {"type", "power", "stock"};

			class type {
				changeingame = 0;
				values[] = {"GL", "Rifle"};

				class GL { label = "GL"; };
				class Rifle { label = "Rifle"; };
			};

			class power {
				changeingame = 0;
				values[] = {"HighPower", "LowPower"};

				class HighPower { label = "HighPower"; };
				class LowPower { label = "LowPower"; };
			};

			class stock {
				changeingame = 0;
				values[] = {"Metal", "Wood"};

				class Metal { label = "Metal"; };
				class Wood { label = "Wood"; };
			};
		};
	};
};
