// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_hpb_base",\
"rri_weapon_hpb",\
"rri_weapon_hpb_bcsewpn",\
"rri_weapons_hpb_hpb_scope"

#define UNIT_LIST \
"rri_weapon_hpb_GH",\
"rri_weapon_hpb_bcsewpn_GH",\
"rri_weapons_hpb_hpb_scope_GH"
