// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_hpb,rri_mag_hpb,"[SOB] HPB-14");
MACRO_GH_WEAPON(rri_weapon_hpb_bcsewpn,rri_mag_hpb,"[SOB] HPB-14");
MACRO_GH_ITEM(rri_weapons_hpb_hpb_scope,"[SOB] HPB Scope");
