// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \

#define UNIT_LIST \
"mti_armoury_props_Prop_Base",\
"mti_armoury_props_banners_Banner_Double_spin_Base",\
"mti_armoury_props_banners_Banner_Single_spin_Base",\
"mti_armoury_props_banners_Banner_Double_Base",\
"mti_armoury_props_banners_Banner_single_Base",\
"mti_armoury_props_banners_Banner_Double_co_spin",\
"mti_armoury_props_banners_Banner_Double_p1_spin",\
"mti_armoury_props_banners_Banner_Double_p2_spin",\
"mti_armoury_props_banners_Banner_Double_fs_spin",\
"mti_armoury_props_banners_Banner_Double_x_spin",\
"mti_armoury_props_banners_Banner_Double_co",\
"mti_armoury_props_banners_Banner_Double_p1",\
"mti_armoury_props_banners_Banner_Double_p2",\
"mti_armoury_props_banners_Banner_Double_fs",\
"mti_armoury_props_banners_Banner_Double_x",\
"mti_armoury_props_banners_Banner_single_co_spin",\
"mti_armoury_props_banners_Banner_single_p1_spin",\
"mti_armoury_props_banners_Banner_single_p2_spin",\
"mti_armoury_props_banners_Banner_single_fs_spin",\
"mti_armoury_props_banners_Banner_single_x_spin",\
"mti_armoury_props_banners_Banner_single_co",\
"mti_armoury_props_banners_Banner_single_p1",\
"mti_armoury_props_banners_Banner_single_p2",\
"mti_armoury_props_banners_Banner_single_fs",\
"mti_armoury_props_banners_Banner_single_x",\
"mti_armoury_props_banners_Banner_fob_core"
