#define VEHICLE_LIST QGVAR(Z95),\
QGVAR(NuClass),\
QGVAR(RhoClass),\
QGVAR(LAAT),\
QGVAR(LAATMK2),\
QGVAR(LAATC),\
QGVAR(Delta7),\
QGVAR(BLTB),\
QGVAR(ARC_170),\
QGVAR(ATTE),\
QGVAR(TX130_Base),\
QGVAR(TX130_Recon),\
QGVAR(TX130_Super)