// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_equipment_custom_bx_trenchcoat",\
"rri_equipment_custom_helmet_Tanker",\
"rri_equipment_custom_helmet_tanker_Illum",\
"rri_equipment_custom_helmet_knight",\
"rri_equipment_custom_nvg_P1_MC_Visor",\
"rri_equipment_custom_nvg_p1_visor",\
"rri_equipment_custom_nvg_P1_advisor_Visor",\
"rri_equipment_custom_nvg_P1_MC_Visor2"

#define UNIT_LIST \
"rri_equipment_custom_backpack_arc",\
"rri_equipment_custom_backpack_arc_noBracer",\
"rri_equipment_custom_backpack_arc_tech",\
"rri_equipment_custom_backpack_arc_tech_noBracer",\
"rri_equipment_custom_backpack_fsb",\
"rri_equipment_custom_backpack_jt12",\
"rri_equipment_custom_backpack_jt12_rocket",\
"rri_equipment_custom_backpack_trooper",\
"rri_equipment_custom_backpack_eod",\
"rri_equipment_custom_backpack_medic",\
"rri_equipment_custom_backpack_rto",\
"rri_equipment_custom_bx_trenchcoat_GH",\
"rri_equipment_custom_helmet_Tanker_GH",\
"rri_equipment_custom_nvg_P1_MC_Visor_GH",\
"rri_equipment_custom_nvg_p1_visor_GH"
