// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_VEST(rri_equipment_custom_bx_trenchcoat,"[SOB] BX Trenchcoat");
MACRO_GH_HEADGEAR(rri_equipment_custom_helmet_Tanker,"[SOB] Tanker Helmet");
MACRO_GH_ITEM(rri_equipment_custom_nvg_P1_MC_Visor,"[SOB] Phase 1 Marshal Commander Visor");
MACRO_GH_ITEM(rri_equipment_custom_nvg_p1_visor,"[SOB] Phase 1 Commander Visor");
