// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_RPS6_HP,rri_mag_RPS6_HP,"[SOB] RPS-6 Heavy Projectile");
