// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_rd4",\
"rri_weapon_rd4_bcsewpn"

#define UNIT_LIST \
"rri_weapon_rd4_GH",\
"rri_weapon_rd4_bcsewpn_GH"
