// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_rd4,rri_mag_rd4,"[SOB] RD-4");
MACRO_GH_WEAPON(rri_weapon_rd4_bcsewpn,rri_mag_rd4,"[SOB] RD-4");
