// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_epl2,rri_mag_epl2,"[SOB] EPL-2 EMP Launcher");
MACRO_GH_WEAPON(rri_weapon_epl2_bcsewpn,rri_mag_epl2,"[SOB] EPL-2 EMP Launcher");
