// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_HH12,rri_mag_HH12_Cluster,"[SOB] HH-12 Rocket Launcher");
