// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_DC17S",\
"rri_weapon_DC17S_ARC",\
"rri_weapon_DC17S_Dual_ARC",\
"rri_weapon_DC17S_Mokka",\
"rri_weapon_DC17S_Dual_Mokka",\
"rri_weapon_DC17MC3C"

#define UNIT_LIST \
"rri_weapon_DC17S_GH",\
"rri_weapon_DC17S_ARC_GH",\
"rri_weapon_DC17S_Dual_ARC_GH",\
"rri_weapon_DC17S_Mokka_GH",\
"rri_weapon_DC17S_Dual_Mokka_GH",\
"rri_weapon_DC17MC3C_GH"
