// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_DC17S,rri_mag_DC17S,"[SOB] DC-17s");
MACRO_GH_WEAPON(rri_weapon_DC17S_ARC,rri_mag_DC17s_ARC,"[SOB] DC-17s ARC");
MACRO_GH_WEAPON(rri_weapon_DC17S_Dual_ARC,rri_mag_DC17s_ARC,"[SOB] DC-17s ARC (Dual)");
MACRO_GH_WEAPON(rri_weapon_DC17S_Mokka,rri_mag_DC17s_ARC,"[SOB] DC-17sm");
MACRO_GH_WEAPON(rri_weapon_DC17S_Dual_Mokka,rri_mag_DC17s_ARC,"[SOB] DC-17sm (Dual)");
MACRO_GH_WEAPON(rri_weapon_DC17MC3C,rri_mag_DC17_mc3c,"[SOB] DC-17MC3C (Celt)");
