// This file is automatically generated by write_aceax_compat.py
// Do not edit this file manually!

class XtdGearModels {
	class CfgWeapons {
		class rri_weapons_dc17s_arc {
			label = ACEAX_LABEL_ARC;
			author = "MokTech Industries";
			options[] = {"type"};

			class type {
				changeingame = 1;
				values[] = {"Dual", "Single"};

				class Dual { label = "Dual"; };
				class Single { label = "Single"; };
			};
		};
		class rri_weapons_dc17s_mokka {
			label = ACEAX_LABEL_MOKKA;
			author = "MokTech Industries";
			options[] = {"type"};

			class type {
				changeingame = 1;
				values[] = {"Dual", "Single"};

				class Dual { label = "Dual"; };
				class Single { label = "Single"; };
			};
		};
	};
};
