// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"mti_armoury_props_intel_datapad_item",\
"mti_armoury_props_intel_antenna_item"

#define UNIT_LIST \
"mti_armoury_props_intel_datapad",\
"mti_armoury_props_intel_Holoprojector",\
"mti_armoury_props_intel_Antenna",\
"mti_armoury_props_intel_DataPad2",\
"mti_armoury_props_intel_datapad_item_GH",\
"mti_armoury_props_intel_antenna_item_GH"
