// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_ITEM(mti_armoury_props_intel_datapad_item,"[SOB] Technician's Datapad");
MACRO_GH_ITEM(mti_armoury_props_intel_antenna_item,"[SOB] Antenna");
