// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_dc17m",\
"rri_weapon_dc17m_bcsewpn"

#define UNIT_LIST \
"rri_weapon_dc17m_GH",\
"rri_weapon_dc17m_bcsewpn_GH"
