// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_dc17m,rri_mag_dc17m,"[SOB] DC-17M");
MACRO_GH_WEAPON(rri_weapon_dc17m_bcsewpn,rri_mag_dc17m,"[SOB] DC-17M");
