// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_HEADGEAR(rri_equipment_jumptrooper_helmet_Cadet,"[SOB] JumpTrooper P1 Helmet (Cadet)");
MACRO_GH_HEADGEAR(rri_equipment_jumptrooper_helmet_Trooper,"[SOB] JumpTrooper P1 Helmet (Trooper)");
MACRO_GH_HEADGEAR(rri_equipment_jumptrooper_helmet_TL,"[SOB] JumpTrooper P1 Helmet (TL)");
MACRO_GH_HEADGEAR(rri_equipment_jumptrooper_helmet_SL,"[SOB] JumpTrooper P1 Helmet (SL)");
MACRO_GH_HEADGEAR(rri_equipment_jumptrooper_helmet_Medic,"[SOB] JumpTrooper P1 Helmet (Medic)");
MACRO_GH_HEADGEAR(rri_equipment_jumptrooper_helmet_EOD,"[SOB] JumpTrooper P1 Helmet (EOD)");
MACRO_GH_ITEM(rri_equipment_jumptrooper_nvg_Visor,"[SOB] JumpTrooper Macrobinoculars");
MACRO_GH_ITEM(rri_equipment_jumptrooper_nvg_Rangefinder,"[SOB] JumpTrooper Rangefinder");
MACRO_GH_UNIFORM(rri_equipment_jumptrooper_uniform_Cadet,"[SOB] Jump Trooper Cadet Armor");
MACRO_GH_UNIFORM(rri_equipment_jumptrooper_uniform_Trooper,"[SOB] Jump Trooper Armor");
MACRO_GH_UNIFORM(rri_equipment_jumptrooper_uniform_TL,"[SOB] Jump Trooper TeamLead Armor");
MACRO_GH_UNIFORM(rri_equipment_jumptrooper_uniform_SL,"[SOB] Jump Trooper Squadlead Armor");
MACRO_GH_UNIFORM(rri_equipment_jumptrooper_uniform_Medic,"[SOB] Jump Trooper Medic Armor");
MACRO_GH_UNIFORM(rri_equipment_jumptrooper_uniform_EOD,"[SOB] Jump Trooper EOD Armor");
MACRO_GH_VEST(rri_equipment_jumptrooper_vest_base,"[SOB] Jump Trooper Vest");
MACRO_GH_VEST(rri_equipment_jumptrooper_vest_Cadet,"[SOB] Jump Trooper Cadet Vest");
MACRO_GH_VEST(rri_equipment_jumptrooper_vest_NCO,"[SOB] Jump Trooper NCO Vest");
MACRO_GH_VEST(rri_equipment_jumptrooper_vest_Medic,"[SOB] Jump Trooper Medic Vest");
MACRO_GH_VEST(rri_equipment_jumptrooper_vest_EOD,"[SOB] Jump Trooper EOD Vest");
