// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \

#define UNIT_LIST \
"rri_props_Prop_Base",\
"rri_props_locker_base",\
"rri_props_locker_jt",\
"rri_props_locker_arc",\
"rri_props_locker_command",\
"rri_props_locker_fs",\
"rri_props_locker_p2",\
"rri_props_locker_pilot",\
"rri_props_locker_rc"
