// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \

#define UNIT_LIST \
"mti_armoury_props_Prop_Base",\
"mti_armoury_props_locker_base",\
"mti_armoury_props_locker_jt",\
"mti_armoury_props_locker_arc",\
"mti_armoury_props_locker_command",\
"mti_armoury_props_locker_fs",\
"mti_armoury_props_locker_p2",\
"mti_armoury_props_locker_pilot",\
"mti_armoury_props_locker_rc"
