// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_causality",\
"rri_weapon_causality_bcsewpn",\
"rri_weapon_causaility_sidearm",\
"rri_weapons_causality_causality_scope"

#define UNIT_LIST \
"rri_weapon_causality_GH",\
"rri_weapon_causality_bcsewpn_GH",\
"rri_weapon_causaility_sidearm_GH",\
"rri_weapons_causality_causality_scope_GH"
