// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_causality,rri_mag_Causality_base,"[SOB] Causality");
MACRO_GH_WEAPON(rri_weapon_causality_bcsewpn,rri_mag_Causality_base,"[SOB] Causality");
MACRO_GH_WEAPON(rri_weapon_causaility_sidearm,rri_mag_causality_precision,"[SOB] Causality Sidearm");
MACRO_GH_ITEM(rri_weapons_causality_causality_scope,"[SOB] Causality Scope");
