// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_t20",\
"rri_weapon_t20_bcsewpn"

#define UNIT_LIST \
"rri_weapon_t20_GH",\
"rri_weapon_t20_bcsewpn_GH"
