// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_t20,rri_mag_t20,"[SOB] T-20 Rifle");
MACRO_GH_WEAPON(rri_weapon_t20_bcsewpn,rri_mag_t20,"[SOB] T-20 Rifle");
