// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_HEADGEAR(rri_equipment_warden_helmet_Trooper,"[SOB] Warden P2 Helmet (CT)");
MACRO_GH_HEADGEAR(rri_equipment_warden_helmet_tanker_CT,"[SOB] Warden Tanker Helmet (CT)");
MACRO_GH_HEADGEAR(rri_equipment_warden_helmet_tanker_SCT,"[SOB] Warden Tanker Helmet (SCT)");
MACRO_GH_HEADGEAR(rri_equipment_warden_helmet_tanker_VCT,"[SOB] Warden Tanker Helmet (VCT)");
MACRO_GH_HEADGEAR(rri_equipment_warden_helmet_tanker_WO1,"[SOB] Warden Tanker Helmet (WO1)");
MACRO_GH_HEADGEAR(rri_equipment_warden_helmet_tanker_WO2,"[SOB] Warden Tanker Helmet (WO2)");
MACRO_GH_HEADGEAR(rri_equipment_warden_helmet_tanker_WO3,"[SOB] Warden Tanker Helmet (WO3)");
MACRO_GH_HEADGEAR(rri_equipment_warden_helmet_tanker_WO4,"[SOB] Warden Tanker Helmet (WO4)");
MACRO_GH_HEADGEAR(rri_equipment_warden_helmet_tanker_WOC,"[SOB] Warden Tanker Helmet (WOC)");
MACRO_GH_HEADGEAR(rri_equipment_warden_helmet_pilot_CT,"[SOB] Warden Pilot Helmet P1 (CT)");
MACRO_GH_HEADGEAR(rri_equipment_warden_helmet_pilot_SCT,"[SOB] Warden Pilot Helmet P1 (SCT)");
MACRO_GH_HEADGEAR(rri_equipment_warden_helmet_pilot_VCT,"[SOB] Warden Pilot Helmet P1 (VCT)");
MACRO_GH_HEADGEAR(rri_equipment_warden_helmet_pilot_WO4,"[SOB] Warden Pilot Helmet P1 (WO4)");
MACRO_GH_HEADGEAR(rri_equipment_warden_helmet_pilot_WO3,"[SOB] Warden Pilot Helmet P1 (WO3)");
MACRO_GH_HEADGEAR(rri_equipment_warden_helmet_pilot_WO2,"[SOB] Warden Pilot Helmet P1 (WO2)");
MACRO_GH_HEADGEAR(rri_equipment_warden_helmet_pilot_WO1,"[SOB] Warden Pilot Helmet P1 (WO1)");
MACRO_GH_HEADGEAR(rri_equipment_warden_helmet_pilot_WOC,"[SOB] Warden Pilot Helmet P1 (WOC)");
MACRO_GH_UNIFORM(rri_equipment_warden_uniform_CT,"[SOB] Field Support Armor (CT)");
MACRO_GH_UNIFORM(rri_equipment_warden_uniform_SCT,"[SOB] Field Support Armor (SCT)");
MACRO_GH_UNIFORM(rri_equipment_warden_uniform_VCT,"[SOB] Field Support Armor (VCT)");
MACRO_GH_UNIFORM(rri_equipment_warden_uniform_WO1,"[SOB] Field Support Armor (WO1)");
MACRO_GH_UNIFORM(rri_equipment_warden_uniform_WO2,"[SOB] Field Support Armor (WO2)");
MACRO_GH_UNIFORM(rri_equipment_warden_uniform_WO3,"[SOB] Field Support Armor (WO3)");
MACRO_GH_UNIFORM(rri_equipment_warden_uniform_WO4,"[SOB] Field Support Armor (WO4)");
MACRO_GH_UNIFORM(rri_equipment_warden_uniform_WOC,"[SOB] Field Support Armor (WOC)");
MACRO_GH_VEST(rri_equipment_warden_vest_base_FS,"[SOB] Field Support Suspenders (Black)");
MACRO_GH_VEST(rri_equipment_warden_vest_white_FS,"[SOB] Field Support Suspenders (White)");
MACRO_GH_VEST(rri_equipment_warden_vest_Grey_FS,"[SOB] Field Support Suspenders (Grey)");
