// This file is automatically generated by write_aceax_compat.py
// Do not edit this file manually!

class XtdGearModels {
	class CfgWeapons {
		class rri_equipment_warden_helmet {
			label = ACEAX_LABEL_HELMET;
			author = "MokTech Industries";
			options[] = {"rank", "camo"};

			class rank {
				changeingame = 0;
				values[] = {"CT", "SCT", "VCT", "WO1", "WO2", "WO3", "WO4", "WOC"};

				class CT { label = "CT"; };
				class SCT { label = "SCT"; };
				class VCT { label = "VCT"; };
				class WO1 { label = "WO1"; };
				class WO2 { label = "WO2"; };
				class WO3 { label = "WO3"; };
				class WO4 { label = "WO4"; };
				class WOC { label = "WOC"; };
			};

			class camo {
				changeingame = 0;
				values[] = {"Pilot", "Tanker"};

				class Pilot { label = "Pilot"; };
				class Tanker { label = "Tanker"; };
			};
		};
		class rri_equipment_warden_uniform {
			label = ACEAX_LABEL_UNIFORM;
			author = "MokTech Industries";
			options[] = {"camo", "rank"};

			class camo {
				changeingame = 0;
				values[] = {"Medic", "Trooper"};

				class Medic { label = "Medic"; };
				class Trooper { label = "Trooper"; };
			};

			class rank {
				changeingame = 0;
				values[] = {"CT", "SCT", "VCT", "WO1", "WO2", "WO3", "WO4", "WOC"};

				class CT { label = "CT"; };
				class SCT { label = "SCT"; };
				class VCT { label = "VCT"; };
				class WO1 { label = "WO1"; };
				class WO2 { label = "WO2"; };
				class WO3 { label = "WO3"; };
				class WO4 { label = "WO4"; };
				class WOC { label = "WOC"; };
			};
		};
		class rri_equipment_warden_vest {
			label = ACEAX_LABEL_VEST;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"Black", "Grey", "White"};

				class Black { label = "Black"; };
				class Grey { label = "Grey"; };
				class White { label = "White"; };
			};
		};
	};
	class CfgVehicles {
		class rri_equipment_warden_backpack {
			label = ACEAX_LABEL_BACKPACK;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"Medic", "Trooper"};

				class Medic { label = "Medic"; };
				class Trooper { label = "Trooper"; };
			};
		};
		class rri_equipment_warden_sp {
			label = ACEAX_LABEL_SP;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"base", "lead", "xray"};

				class base { label = "base"; };
				class lead { label = "lead"; };
				class xray { label = "xray"; };
			};
		};
	};
};
