// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_br_77_base",\
"rri_weapon_br_77_wood",\
"rri_weapon_br_77_metal",\
"rri_weapon_br_77_wood_bcsewpn",\
"rri_weapon_br_77_metal_bcsewpn",\
"rri_weapons_br77_br_77_scope",\
"rri_weapons_br77_br_77_bayonet",\
"rri_weapons_br77_br_77_supressor"

#define UNIT_LIST \
"rri_weapon_br_77_wood_GH",\
"rri_weapon_br_77_metal_GH",\
"rri_weapon_br_77_wood_bcsewpn_GH",\
"rri_weapon_br_77_metal_bcsewpn_GH",\
"rri_weapons_br77_br_77_scope_GH",\
"rri_weapons_br77_br_77_bayonet_GH",\
"rri_weapons_br77_br_77_supressor_GH"
