// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_br_77_wood,rri_mag_br77_HP,"[SOB] BR-77 (Wooden)");
MACRO_GH_WEAPON(rri_weapon_br_77_metal,rri_mag_br77_HP,"[SOB] BR-77 (Metal)");
MACRO_GH_WEAPON(rri_weapon_br_77_wood_bcsewpn,rri_mag_br77_HP,"[SOB] BR-77 (Wooden)");
MACRO_GH_WEAPON(rri_weapon_br_77_metal_bcsewpn,rri_mag_br77_HP,"[SOB] BR-77 (Metal)");
MACRO_GH_ITEM(rri_weapons_br77_br_77_scope,"[SOB] BR-77 Scope");
MACRO_GH_ITEM(rri_weapons_br77_br_77_bayonet,"[SOB] BR-77 Bayonet");
MACRO_GH_ITEM(rri_weapons_br77_br_77_supressor,"[SOB] BR-77 Supressor");
