// This file is automatically generated by write_aceax_compat.py
// Do not edit this file manually!

class XtdGearModels {
	class CfgWeapons {
		class rri_weapons_br77_BR77 {
			label = ACEAX_LABEL_BR77;
			author = "MokTech Industries";
			options[] = {"type"};

			class type {
				changeingame = 0;
				values[] = {"Metal", "Wood"};

				class Metal { label = "Metal"; };
				class Wood { label = "Wood"; };
			};
		};
	};
};
