// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_z6",\
"rri_weapon_z6_heavy",\
"rri_weapon_z6_bcsewpn",\
"rri_weapon_z6_heavy_bcsewpn"

#define UNIT_LIST \
"rri_weapon_z6_GH",\
"rri_weapon_z6_heavy_GH",\
"rri_weapon_z6_bcsewpn_GH",\
"rri_weapon_z6_heavy_bcsewpn_GH"
