// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_z6,rri_mag_z6,"[SOB] Z-6");
MACRO_GH_WEAPON(rri_weapon_z6_heavy,rri_mag_z6,"[SOB] Heavy Z-6");
MACRO_GH_WEAPON(rri_weapon_z6_bcsewpn,rri_mag_z6,"[SOB] Z-6");
MACRO_GH_WEAPON(rri_weapon_z6_heavy_bcsewpn,rri_mag_z6,"[SOB] Heavy Z-6");
