// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_DC15S",\
"rri_weapon_DC15S_HP",\
"rri_weapon_DC15S_GL",\
"rri_weapon_DC15S_HP_GL",\
"rri_weapon_DC15S_Shield",\
"rri_weapon_DC15S_HP_Shield",\
"rri_weapon_DC19S",\
"rri_weapon_DC15S_bcsewpn",\
"rri_weapon_DC15S_GL_bcsewpn",\
"rri_weapon_DC15S_HP_bcsewpn",\
"rri_weapon_DC15S_HP_GL_bcsewpn",\
"rri_weapon_DC19S_bcsewpn"

#define UNIT_LIST \
"rri_weapon_DC15S_GH",\
"rri_weapon_DC15S_HP_GH",\
"rri_weapon_DC15S_GL_GH",\
"rri_weapon_DC15S_HP_GL_GH",\
"rri_weapon_DC19S_GH",\
"rri_weapon_DC15S_bcsewpn_GH",\
"rri_weapon_DC15S_GL_bcsewpn_GH",\
"rri_weapon_DC15S_HP_bcsewpn_GH",\
"rri_weapon_DC15S_HP_GL_bcsewpn_GH",\
"rri_weapon_DC19S_bcsewpn_GH"
