// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_DC15S,rri_mag_DC15S,"[SOB] DC-15S");
MACRO_GH_WEAPON(rri_weapon_DC15S_HP,rri_mag_DC15S_HP,"[SOB] DC-15S High Power");
MACRO_GH_WEAPON(rri_weapon_DC15S_GL,rri_mag_DC15S,"[SOB] DC-15S GL");
MACRO_GH_WEAPON(rri_weapon_DC15S_HP_GL,rri_mag_DC15S_HP,"[SOB] DC-15S Highpower GL");
MACRO_GH_WEAPON(rri_weapon_DC19S,rri_mag_DC15S,"[SOB] DC-19S");
MACRO_GH_WEAPON(rri_weapon_DC15S_bcsewpn,rri_mag_DC15S,"[SOB] DC-15S");
MACRO_GH_WEAPON(rri_weapon_DC15S_GL_bcsewpn,rri_mag_DC15S,"[SOB] DC-15S GL");
MACRO_GH_WEAPON(rri_weapon_DC15S_HP_bcsewpn,rri_mag_DC15S_HP,"[SOB] DC-15S High Power");
MACRO_GH_WEAPON(rri_weapon_DC15S_HP_GL_bcsewpn,rri_mag_DC15S_HP,"[SOB] DC-15S Highpower GL");
MACRO_GH_WEAPON(rri_weapon_DC19S_bcsewpn,rri_mag_DC15S,"[SOB] DC-19S");
