// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_westarm5",\
"rri_weapon_westarm5_gl",\
"rri_weapon_westarm5_bcsewpn",\
"rri_weapon_westarm5_gl_bcsewpn"

#define UNIT_LIST \
"rri_weapon_westarm5_GH",\
"rri_weapon_westarm5_gl_GH",\
"rri_weapon_westarm5_bcsewpn_GH",\
"rri_weapon_westarm5_gl_bcsewpn_GH"
