// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_westarm5,rri_mag_westarm5,"[SOB] Westar M5");
MACRO_GH_WEAPON(rri_weapon_westarm5_gl,rri_mag_westarm5,"[SOB] Westar M5 GL");
MACRO_GH_WEAPON(rri_weapon_westarm5_bcsewpn,rri_mag_westarm5,"[SOB] Westar M5");
MACRO_GH_WEAPON(rri_weapon_westarm5_gl_bcsewpn,rri_mag_westarm5,"[SOB] Westar M5 GL");
