// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_arkanian",\
"rri_weapon_arkanian_bcsewpn"

#define UNIT_LIST \
"rri_weapon_arkanian_GH",\
"rri_weapon_arkanian_bcsewpn_GH"
