// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_arkanian,rri_mag_arkanian,"[SOB] Arkanian Rifle");
MACRO_GH_WEAPON(rri_weapon_arkanian_bcsewpn,rri_mag_arkanian,"[SOB] Arkanian Rifle");
