// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_DC15LE",\
"rri_weapon_DC15LE_HP",\
"rri_weapons_dc15le_DC15LE_muzzle",\
"rri_weapon_DC19LE",\
"rri_weapon_DC15LE_bcsewpn",\
"rri_weapon_DC15LE_HP_bcsewpn",\
"rri_weapon_DC19LE_bcsewpn"

#define UNIT_LIST \
"rri_weapon_DC15LE_GH",\
"rri_weapon_DC15LE_HP_GH",\
"rri_weapon_DC19LE_GH",\
"rri_weapon_DC15LE_bcsewpn_GH",\
"rri_weapon_DC15LE_HP_bcsewpn_GH",\
"rri_weapon_DC19LE_bcsewpn_GH"
