// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_DC15LE,rri_mag_DC15LE_HP,"[SOB] DC-15LE");
MACRO_GH_WEAPON(rri_weapon_DC15LE_HP,rri_mag_DC15LE,"[SOB] DC-15LE High Power");
MACRO_GH_WEAPON(rri_weapon_DC19LE,rri_mag_DC15LE_HP,"[SOB] DC-19LE");
MACRO_GH_WEAPON(rri_weapon_DC15LE_bcsewpn,rri_mag_DC15LE_HP,"[SOB] DC-15LE");
MACRO_GH_WEAPON(rri_weapon_DC15LE_HP_bcsewpn,rri_mag_DC15LE,"[SOB] DC-15LE High Power");
MACRO_GH_WEAPON(rri_weapon_DC19LE_bcsewpn,rri_mag_DC15LE_HP,"[SOB] DC-19LE");
