// This file is automatically generated by write_aceax_compat.py
// Do not edit this file manually!

class XtdGearModels {
	class CfgGlasses {
		class rri_equipment_arc_FW {
			label = ACEAX_LABEL_FW;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"AlphaMacro", "AlphaRangefinder", "Rangefinder"};

				class AlphaMacro { label = "AlphaMacro"; };
				class AlphaRangefinder { label = "AlphaRangefinder"; };
				class Rangefinder { label = "Rangefinder"; };
			};
		};
	};
	class CfgWeapons {
		class rri_equipment_arc_helmet {
			label = ACEAX_LABEL_HELMET;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"Cadet", "Demo", "Medic", "SL", "Trooper"};

				class Cadet { label = "Cadet"; };
				class Demo { label = "Demo"; };
				class Medic { label = "Medic"; };
				class SL { label = "SL"; };
				class Trooper { label = "Trooper"; };
			};
		};
		class rri_equipment_arc_alpha_nvg {
			label = ACEAX_LABEL_ALPHA_NVG;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"CL", "CS", "Macrobinocular", "NCO", "White"};

				class CL { label = "CL"; };
				class CS { label = "CS"; };
				class Macrobinocular { label = "Macrobinocular"; };
				class NCO { label = "NCO"; };
				class White { label = "White"; };
			};
		};
		class rri_equipment_arc_arc_range {
			label = ACEAX_LABEL_ARC_RANGE;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"Rangefinder"};

				class Rangefinder { label = "Rangefinder"; };
			};
		};
		class rri_equipment_arc_uniform {
			label = ACEAX_LABEL_UNIFORM;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"Cadet", "Demo", "Medic", "SL", "Trooper"};

				class Cadet { label = "Cadet"; };
				class Demo { label = "Demo"; };
				class Medic { label = "Medic"; };
				class SL { label = "SL"; };
				class Trooper { label = "Trooper"; };
			};
		};
		class rri_equipment_arc_vest {
			label = ACEAX_LABEL_VEST;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"Cadet", "Demo", "Medic", "SL", "TL", "Trooper"};

				class Cadet { label = "Cadet"; };
				class Demo { label = "Demo"; };
				class Medic { label = "Medic"; };
				class SL { label = "SL"; };
				class TL { label = "TL"; };
				class Trooper { label = "Trooper"; };
			};
		};
	};
};
