// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_ITEM(rri_weapons_core_EE2_Scope,"[SOB] EE-2 Rifle Scope");
MACRO_GH_ITEM(rri_weapons_core_HLRPS_Blue,"[SOB] MokTech Holo-LRPS (Blue)");
MACRO_GH_ITEM(rri_weapons_core_HLRPS_Green,"[SOB] MokTech Holo-LRPS (Green)");
MACRO_GH_ITEM(rri_weapons_core_HLRPS_Red,"[SOB] MokTech Holo-LRPS (Red)");
MACRO_GH_ITEM(rri_weapons_core_HDMS_Blue,"[SOB] MokTech Holo-DMS (Blue)");
MACRO_GH_ITEM(rri_weapons_core_HDMS_Green,"[SOB] MokTech Holo-DMS (Green)");
MACRO_GH_ITEM(rri_weapons_core_HDMS_Red,"[SOB] MokTech Holo-DMS (Red)");
MACRO_GH_ITEM(rri_weapons_core_HMRCO_Blue,"[SOB] MokTech Holo-MRCO (Blue)");
MACRO_GH_ITEM(rri_weapons_core_HMRCO_Green,"[SOB] MokTech Holo-MRCO (Green)");
MACRO_GH_ITEM(rri_weapons_core_HMRCO_Red,"[SOB] MokTech Holo-MRCO (Red)");
MACRO_GH_ITEM(rri_weapons_core_HMRD_Blue,"[SOB] MokTech Holo-MRD (Blue)");
MACRO_GH_ITEM(rri_weapons_core_HMRD_Green,"[SOB] MokTech Holo-MRD (Green)");
MACRO_GH_ITEM(rri_weapons_core_HMRD_Red,"[SOB] MokTech Holo-MRD (Red)");
MACRO_GH_ITEM(rri_weapons_core_Holo_Blue,"[SOB] MokTech Holosight (Blue)");
MACRO_GH_ITEM(rri_weapons_core_Holo_Green,"[SOB] MokTech Holosight (Green)");
MACRO_GH_ITEM(rri_weapons_core_Holo_Red,"[SOB] MokTech Holosight (Red)");
MACRO_GH_ITEM(rri_weapons_core_HRCO_Blue,"[SOB] MokTech Holo-RCO (Blue)");
MACRO_GH_ITEM(rri_weapons_core_HRCO_Green,"[SOB] MokTech Holo-RCO (Green)");
MACRO_GH_ITEM(rri_weapons_core_HRCO_Red,"[SOB] MokTech Holo-RCO (Red)");
MACRO_GH_ITEM(rri_weapons_core_MRCO,"[SOB] BlasTech MRCO");
MACRO_GH_ITEM(rri_weapons_core_SOS,"[SOB] BlasTech MOS");
MACRO_GH_ITEM(rri_weapons_core_LRPSX,"[SOB] BlasTech LRPS-X Scope");
MACRO_GH_ITEM(rri_weapons_core_reflex,"[SOB] Merr-Sonn Reflex Sight");
MACRO_GH_ITEM(rri_weapons_core_ACOG_2,"[SOB] Merr-Sonn ACOG Scope");
MACRO_GH_ITEM(rri_weapons_core_ERCO,"[SOB] Merr-Sonn ERCO Scope");
MACRO_GH_ITEM(rri_weapons_core_KHS,"[SOB] Merr-Sonn KHS Scope");
MACRO_GH_ITEM(rri_weapons_core_LRPS,"[SOB] Merr-Sonn LRPS Scope");
MACRO_GH_ITEM(rri_weapons_core_ACOG,"[SOB] BlasTech ACOG Scope");
MACRO_GH_ITEM(rri_weapons_core_ACOGMG,"[SOB] BlasTech ACOG MG Scope");
MACRO_GH_ITEM(rri_weapons_core_Flashlight_nomodel,"Flashlight (No Model)");
MACRO_GH_ITEM(rri_weapons_core_Pointer_IR_nomdel,"Laser Pointer (No Model)");
MACRO_GH_ITEM(rri_weapons_core_Pointer_IR,"Laser Pointer");
MACRO_GH_ITEM(rri_weapons_core_Silencer,"[SOB] 19-Series Stealth Muzzle");
