// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_ls150",\
"rri_weapon_ls150_bcsewpn"

#define UNIT_LIST \
"rri_weapon_ls150_GH",\
"rri_weapon_ls150_bcsewpn_GH"
