// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_ls150,rri_mag_ls150,"[SOB] LS-150 Heavy Repeater");
MACRO_GH_WEAPON(rri_weapon_ls150_bcsewpn,rri_mag_ls150,"[SOB] LS-150 Heavy Repeater");
