// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_HEADGEAR(rri_equipment_arc_helmet_cadet,"[SOB] ARC Cadet Helmet");
MACRO_GH_HEADGEAR(rri_equipment_arc_helmet_trooper,"[SOB] ARC Trooper Helmet");
MACRO_GH_HEADGEAR(rri_equipment_arc_helmet_demo,"[SOB] ARC Trooper Helmet (Demo)");
MACRO_GH_HEADGEAR(rri_equipment_arc_helmet_medic,"[SOB] ARC Trooper Helmet (Medic)");
MACRO_GH_HEADGEAR(rri_equipment_arc_helmet_SL,"[SOB] ARC Trooper Helmet (Squad Leader)");
MACRO_GH_ITEM(rri_equipment_arc_nvg_alpha_range,"[SOB] Alpha-ARC Rangefinder");
MACRO_GH_ITEM(rri_equipment_arc_nvg_alpha_NCO,"[SOB] Alpha-ARC Rangefinder (NCO)");
MACRO_GH_ITEM(rri_equipment_arc_nvg_alpha_CS,"[SOB] Alpha-ARC Rangefinder (CS)");
MACRO_GH_ITEM(rri_equipment_arc_nvg_alpha_CL,"[SOB] Alpha-ARC Rangefinder (CL)");
MACRO_GH_ITEM(rri_equipment_arc_nvg_alpha_macro,"[SOB] Alpha-ARC Macrobinocular");
MACRO_GH_ITEM(rri_equipment_arc_nvg_range,"[SOB] ARC Trooper Rangefinder");
MACRO_GH_UNIFORM(rri_equipment_arc_uniform_cadet,"[SOB] ARC Cadet Armor");
MACRO_GH_UNIFORM(rri_equipment_arc_uniform_trooper,"[SOB] ARC Trooper Armor");
MACRO_GH_UNIFORM(rri_equipment_arc_uniform_demo,"[SOB] ARC Trooper Armor (Demo)");
MACRO_GH_UNIFORM(rri_equipment_arc_uniform_medic,"[SOB] ARC Trooper Armor (Medic)");
MACRO_GH_UNIFORM(rri_equipment_arc_uniform_SL,"[SOB] ARC Trooper Armor (Squad Leader)");
MACRO_GH_VEST(rri_equipment_arc_vest_cadet,"[SOB] ARC Cadet Vest");
MACRO_GH_VEST(rri_equipment_arc_vest_trooper,"[SOB] ARC Trooper Vest");
MACRO_GH_VEST(rri_equipment_arc_vest_demo,"[SOB] ARC Trooper Vest (Demo)");
MACRO_GH_VEST(rri_equipment_arc_vest_medic,"[SOB] ARC Trooper Vest (Medic)");
MACRO_GH_VEST(rri_equipment_arc_vest_tl,"[SOB] ARC Trooper Vest (Team Leader)");
MACRO_GH_VEST(rri_equipment_arc_vest_sl,"[SOB] ARC Trooper Vest (Squad Leader)");
