// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_DC15X",\
"rri_weapon_DC19X",\
"rri_weapon_DC15X_bcsewpn",\
"rri_weapon_DC19X_bcsewpn"

#define UNIT_LIST \
"rri_weapon_DC15X_GH",\
"rri_weapon_DC19X_GH",\
"rri_weapon_DC15X_bcsewpn_GH",\
"rri_weapon_DC19X_bcsewpn_GH"
