// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_DC15X,rri_mag_DC15X,"[SOB] DC-15X");
MACRO_GH_WEAPON(rri_weapon_DC19X,rri_mag_DC15X,"[SOB] DC-19X");
MACRO_GH_WEAPON(rri_weapon_DC15X_bcsewpn,rri_mag_DC15X,"[SOB] DC-15X");
MACRO_GH_WEAPON(rri_weapon_DC19X_bcsewpn,rri_mag_DC15X,"[SOB] DC-19X");
