// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_dc15sa",\
"rri_weapon_dc19sa"

#define UNIT_LIST \
"rri_weapon_dc15sa_GH"
