// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_rsfk44_base",\
"rri_weapon_rsfk44"

#define UNIT_LIST \
"rri_weapon_rsfk44_GH"
