// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_rsfk44,rri_mag_RSKF44,"[SOB] RSKF-44 (Single Barrel)");
