// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_DW32S",\
"rri_weapon_DW32S_bcsewpn"

#define UNIT_LIST \
"rri_weapon_DW32S_GH",\
"rri_weapon_DW32S_bcsewpn_GH"
