// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_DW32S,rri_mag_DW32S,"[SOB] DW-32S");
MACRO_GH_WEAPON(rri_weapon_DW32S_bcsewpn,rri_mag_DW32S,"[SOB] DW-32S");
