// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"mti_armoury_weapon_mm9_HE",\
"mti_armoury_weapon_mm9_stun",\
"mti_armoury_weapon_mm9_ion",\
"mti_armoury_weapon_mm9_smoke",\
"mti_armoury_weapon_mm9_dumb"

#define UNIT_LIST \
"mti_armoury_props_munitions_base",\
"mti_armoury_props_munitions_cluster",\
"mti_armoury_props_munitions_aa",\
"mti_armoury_props_munitions_heat",\
"mti_armoury_props_munitions_mortar",\
"mti_armoury_props_munitions_missile1",\
"mti_armoury_props_munitions_missile2",\
"mti_armoury_props_munitions_missile3",\
"mti_armoury_props_munitions_mm9",\
"mti_armoury_props_munitions_smoke_grenade",\
"mti_armoury_props_munitions_smoke_grenade_Blue",\
"mti_armoury_props_munitions_smoke_grenade_Green",\
"mti_armoury_props_munitions_smoke_grenade_Light_Blue",\
"mti_armoury_props_munitions_smoke_grenade_Orange",\
"mti_armoury_props_munitions_smoke_grenade_Pink",\
"mti_armoury_props_munitions_smoke_grenade_Purple",\
"mti_armoury_props_munitions_smoke_grenade_Red",\
"mti_armoury_props_munitions_smoke_grenade_White",\
"mti_armoury_props_munitions_smoke_grenade_Yellow"
