// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_mm9_HE",\
"rri_weapon_mm9_stun",\
"rri_weapon_mm9_ion",\
"rri_weapon_mm9_smoke",\
"rri_weapon_mm9_dumb"

#define UNIT_LIST \
"rri_props_munitions_base",\
"rri_props_munitions_cluster",\
"rri_props_munitions_aa",\
"rri_props_munitions_heat",\
"rri_props_munitions_mortar",\
"rri_props_munitions_missile1",\
"rri_props_munitions_missile2",\
"rri_props_munitions_missile3",\
"rri_props_munitions_mm9",\
"rri_props_munitions_smoke_grenade",\
"rri_props_munitions_smoke_grenade_Blue",\
"rri_props_munitions_smoke_grenade_Green",\
"rri_props_munitions_smoke_grenade_Light_Blue",\
"rri_props_munitions_smoke_grenade_Orange",\
"rri_props_munitions_smoke_grenade_Pink",\
"rri_props_munitions_smoke_grenade_Purple",\
"rri_props_munitions_smoke_grenade_Red",\
"rri_props_munitions_smoke_grenade_White",\
"rri_props_munitions_smoke_grenade_Yellow"
