// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_ITEM(mti_armoury_weapon_mm9_HE,"[SOB] MM9 HE Rocket");
MACRO_GH_ITEM(mti_armoury_weapon_mm9_stun,"[SOB] MM9 Stun Rocket");
MACRO_GH_ITEM(mti_armoury_weapon_mm9_ion,"[SOB] MM9 Ion Rocket");
MACRO_GH_ITEM(mti_armoury_weapon_mm9_smoke,"[SOB] MM9 Smoke Rocket");
MACRO_GH_ITEM(mti_armoury_weapon_mm9_dumb,"[SOB] MM9 Training Rocket");
