// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_acpr",\
"rri_weapon_acpr_bcsewpn"

#define UNIT_LIST \
"rri_weapon_acpr_GH",\
"rri_weapon_acpr_bcsewpn_GH"
