// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_acpr,rri_mag_ACPR,"[SOB] ACP-Repeater");
MACRO_GH_WEAPON(rri_weapon_acpr_bcsewpn,rri_mag_ACPR,"[SOB] ACP-Repeater");
