// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_EE2",\
"rri_weapon_EE2_bcsewpn"

#define UNIT_LIST \
"rri_weapon_EE2_GH",\
"rri_weapon_EE2_bcsewpn_GH"
