// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_EE2,rri_mag_EE2,"[SOB] EE-2 Blaster Rifle");
MACRO_GH_WEAPON(rri_weapon_EE2_bcsewpn,rri_mag_EE2,"[SOB] EE-2 Blaster Rifle");
