// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_dp23",\
"rri_weapon_dp23_shield",\
"rri_weapon_dp23_hp",\
"rri_weapon_dp23_hp_shield",\
"rri_weapon_dp23_bcsewpn",\
"rri_weapon_dp23_hp_bcsewpn"

#define UNIT_LIST \
"rri_weapon_dp23_GH",\
"rri_weapon_dp23_hp_GH",\
"rri_weapon_dp23_bcsewpn_GH",\
"rri_weapon_dp23_hp_bcsewpn_GH"
