// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_dp23,rri_mag_dp23_buck,"[SOB] DP-23");
MACRO_GH_WEAPON(rri_weapon_dp23_hp,rri_mag_dp23_hp_slug,"[SOB] DP-23 HP");
MACRO_GH_WEAPON(rri_weapon_dp23_bcsewpn,rri_mag_dp23_buck,"[SOB] DP-23");
MACRO_GH_WEAPON(rri_weapon_dp23_hp_bcsewpn,rri_mag_dp23_hp_slug,"[SOB] DP-23 HP");
