// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_boltblaster_base,rri_mag_boltblaster_buck,"[SOB] Boltblaster");
MACRO_GH_WEAPON(rri_weapon_boltblaster_base_bcsewpn,rri_mag_boltblaster_buck,"[SOB] Boltblaster");
