// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_defib_base",\
"rri_weapon_defib"

#define UNIT_LIST \
"rri_weapon_defib_GH"
