// This file is automatically generated by write_aceax_compat.py
// Do not edit this file manually!

class XtdGearModels {
	class CfgGlasses {
		class rri_equipment_commando_FW_Commando {
			label = ACEAX_LABEL_FW_COMMANDO;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"EOD", "SL", "Sniper", "Tech", "Vest", "Visor White"};

				class EOD { label = "EOD"; };
				class SL { label = "SL"; };
				class Sniper { label = "Sniper"; };
				class Tech { label = "Tech"; };
				class Vest { label = "Vest"; };
				class Visor_White { label = "Visor White"; };
			};
		};
	};
	class CfgWeapons {
		class rri_equipment_commando_helmet {
			label = ACEAX_LABEL_HELMET;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"Arctic", "Base", "Cadet", "Desert", "EOD", "Exotic", "Heavy", "Imperial", "Jungle", "Medic", "Night", "SL", "Sarge", "Sniper", "Tech"};

				class Arctic { label = "Arctic"; };
				class Base { label = "Base"; };
				class Cadet { label = "Cadet"; };
				class Desert { label = "Desert"; };
				class EOD { label = "EOD"; };
				class Exotic { label = "Exotic"; };
				class Heavy { label = "Heavy"; };
				class Imperial { label = "Imperial"; };
				class Jungle { label = "Jungle"; };
				class Medic { label = "Medic"; };
				class Night { label = "Night"; };
				class SL { label = "SL"; };
				class Sarge { label = "Sarge"; };
				class Sniper { label = "Sniper"; };
				class Tech { label = "Tech"; };
			};
		};
		class rri_equipment_commando_uniform {
			label = ACEAX_LABEL_UNIFORM;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"Arctic", "Base", "Cadet", "Desert", "EOD", "Exotic", "Heavy", "Imperial", "Jungle", "Medic", "Night", "SL", "Sarge", "Sniper", "Tech"};

				class Arctic { label = "Arctic"; };
				class Base { label = "Base"; };
				class Cadet { label = "Cadet"; };
				class Desert { label = "Desert"; };
				class EOD { label = "EOD"; };
				class Exotic { label = "Exotic"; };
				class Heavy { label = "Heavy"; };
				class Imperial { label = "Imperial"; };
				class Jungle { label = "Jungle"; };
				class Medic { label = "Medic"; };
				class Night { label = "Night"; };
				class SL { label = "SL"; };
				class Sarge { label = "Sarge"; };
				class Sniper { label = "Sniper"; };
				class Tech { label = "Tech"; };
			};
		};
		class rri_equipment_commando_vest {
			label = ACEAX_LABEL_VEST;
			author = "MokTech Industries";
			options[] = {"role", "camo"};

			class role {
				changeingame = 0;
				values[] = {"Base", "Cadet", "EOD", "SL", "Sniper", "Tech"};

				class Base { label = "Base"; };
				class Cadet { label = "Cadet"; };
				class EOD { label = "EOD"; };
				class SL { label = "SL"; };
				class Sniper { label = "Sniper"; };
				class Tech { label = "Tech"; };
			};

			class camo {
				changeingame = 0;
				values[] = {"White"};

				class White { label = "White"; };
			};
		};
	};
	class CfgVehicles {
		class rri_equipment_commando_backpack {
			label = ACEAX_LABEL_BACKPACK;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"Arctic", "Base", "Cadet", "Desert", "EOD", "Imperial", "Imperial_EOD", "Imperial_RTO", "Imperial_Tech", "Jungle", "Night", "RTO", "SOB_EOD", "SOB_Exotic", "SOB_Heavy", "SOB_Medic", "SOB_SL", "SOB_Sniper", "SOB_Tech", "Sarge", "Tech"};

				class Arctic { label = "Arctic"; };
				class Base { label = "Base"; };
				class Cadet { label = "Cadet"; };
				class Desert { label = "Desert"; };
				class EOD { label = "EOD"; };
				class Imperial { label = "Imperial"; };
				class Imperial_EOD { label = "Imperial EOD"; };
				class Imperial_RTO { label = "Imperial RTO"; };
				class Imperial_Tech { label = "Imperial Tech"; };
				class Jungle { label = "Jungle"; };
				class Night { label = "Night"; };
				class RTO { label = "RTO"; };
				class SOB_EOD { label = "SOB EOD"; };
				class SOB_Exotic { label = "SOB Exotic"; };
				class SOB_Heavy { label = "SOB Heavy"; };
				class SOB_Medic { label = "SOB Medic"; };
				class SOB_SL { label = "SOB SL"; };
				class SOB_Sniper { label = "SOB Sniper"; };
				class SOB_Tech { label = "SOB Tech"; };
				class Sarge { label = "Sarge"; };
				class Tech { label = "Tech"; };
			};
		};
	};
};
