// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_plx1,rri_mag_plx1_at,"[SOB] PLX-1 Guided Missile Launcher Platform");
