// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_MPL",\
"rri_weapon_MPL_bcsewpn"

#define UNIT_LIST \
"rri_weapon_MPL_GH",\
"rri_weapon_MPL_bcsewpn_GH"
