// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_MPL,rri_mag_40mm_AP,"[SOB] MPL Grenade Launcher");
MACRO_GH_WEAPON(rri_weapon_MPL_bcsewpn,rri_mag_40mm_AP,"[SOB] MPL Grenade Launcher");
