// This file is automatically generated by write_aceax_compat.py
// Do not edit this file manually!

class XtdGearModels {
	class CfgGlasses {
		class rri_equipment_trooper_FW_Trooper {
			label = ACEAX_LABEL_FW_TROOPER;
			author = "MokTech Industries";
			options[] = {"style", "color"};

			class style {
				changeingame = 0;
				values[] = {"Macrobinoculars", "RangeFinder", "Specialist Macrobinoculars"};

				class Macrobinoculars { label = "Macrobinoculars"; };
				class RangeFinder { label = "RangeFinder"; };
				class Specialist_Macrobinoculars { label = "Specialist Macrobinoculars"; };
			};

			class color {
				changeingame = 0;
				values[] = {"EOD", "Grey", "Medic", "NCO", "White"};

				class EOD { label = "EOD"; };
				class Grey { label = "Grey"; };
				class Medic { label = "Medic"; };
				class NCO { label = "NCO"; };
				class White { label = "White"; };
			};
		};
	};
	class CfgWeapons {
		class rri_equipment_trooper_helmet {
			label = ACEAX_LABEL_HELMET;
			author = "MokTech Industries";
			options[] = {"rank", "mos"};

			class rank {
				changeingame = 0;
				values[] = {"CL", "CLC", "CP", "CR", "CS", "CSM", "CSP", "CT", "Captain", "Commander", "SCT", "VCT"};

				class CL { label = "CL"; };
				class CLC { label = "CLC"; };
				class CP { label = "CP"; };
				class CR { label = "CR"; };
				class CS { label = "CS"; };
				class CSM { label = "CSM"; };
				class CSP { label = "CSP"; };
				class CT { label = "CT"; };
				class Captain { label = "Captain"; };
				class Commander { label = "Commander"; };
				class SCT { label = "SCT"; };
				class VCT { label = "VCT"; };
			};

			class mos {
				changeingame = 0;
				values[] = {"base", "eod", "medic"};

				class base { label = "base"; };
				class eod { label = "eod"; };
				class medic { label = "medic"; };
			};
		};
		class rri_equipment_trooper_nvg_macro {
			label = ACEAX_LABEL_NVG_MACRO;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"EOD", "Grey", "Medic", "NCO", "White"};

				class EOD { label = "EOD"; };
				class Grey { label = "Grey"; };
				class Medic { label = "Medic"; };
				class NCO { label = "NCO"; };
				class White { label = "White"; };
			};
		};
		class rri_equipment_trooper_nvg_spec {
			label = ACEAX_LABEL_NVG_SPEC;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"EOD", "Grey", "Medic", "NCO", "White"};

				class EOD { label = "EOD"; };
				class Grey { label = "Grey"; };
				class Medic { label = "Medic"; };
				class NCO { label = "NCO"; };
				class White { label = "White"; };
			};
		};
		class rri_equipment_trooper_nvg_range {
			label = ACEAX_LABEL_NVG_RANGE;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"EOD", "Grey", "Medic", "NCO", "White"};

				class EOD { label = "EOD"; };
				class Grey { label = "Grey"; };
				class Medic { label = "Medic"; };
				class NCO { label = "NCO"; };
				class White { label = "White"; };
			};
		};
		class rri_equipment_trooper_uniform {
			label = ACEAX_LABEL_UNIFORM;
			author = "MokTech Industries";
			options[] = {"rank", "mos"};

			class rank {
				changeingame = 0;
				values[] = {"CL", "CLC", "CP", "CR", "CS", "CSM", "CSP", "CT", "Captain", "Commander", "SCT", "VCT"};

				class CL { label = "CL"; };
				class CLC { label = "CLC"; };
				class CP { label = "CP"; };
				class CR { label = "CR"; };
				class CS { label = "CS"; };
				class CSM { label = "CSM"; };
				class CSP { label = "CSP"; };
				class CT { label = "CT"; };
				class Captain { label = "Captain"; };
				class Commander { label = "Commander"; };
				class SCT { label = "SCT"; };
				class VCT { label = "VCT"; };
			};

			class mos {
				changeingame = 0;
				values[] = {"base", "eod", "medic"};

				class base { label = "base"; };
				class eod { label = "eod"; };
				class medic { label = "medic"; };
			};
		};
		class rri_equipment_trooper_rank_vest {
			label = ACEAX_LABEL_RANK_VEST;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"CLC", "CP", "CS", "CSP", "Company", "Holster", "Platoon", "SCT"};

				class CLC { label = "CLC"; };
				class CP { label = "CP"; };
				class CS { label = "CS"; };
				class CSP { label = "CSP"; };
				class Company { label = "Company"; };
				class Holster { label = "Holster"; };
				class Platoon { label = "Platoon"; };
				class SCT { label = "SCT"; };
			};
		};
	};
	class CfgVehicles {
		class rri_equipment_trooper_backpack {
			label = ACEAX_LABEL_BACKPACK;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"Base", "Belt", "EOD", "LR_attachment", "Medic", "RTO", "RTO_Clear", "RTO_pack", "RTO_pack_dark_grey"};

				class Base { label = "Base"; };
				class Belt { label = "Belt"; };
				class EOD { label = "EOD"; };
				class LR_attachment { label = "LR attachment"; };
				class Medic { label = "Medic"; };
				class RTO { label = "RTO"; };
				class RTO_Clear { label = "RTO Clear"; };
				class RTO_pack { label = "RTO pack"; };
				class RTO_pack_dark_grey { label = "RTO pack dark grey"; };
			};
		};
	};
};
