// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_DC15C",\
"rri_weapon_DC15C_HP",\
"rri_weapon_DC15C_GL",\
"rri_weapon_DC15C_HP_GL",\
"rri_weapon_DC19C",\
"rri_weapon_DC15C_bcsewpn",\
"rri_weapon_DC15C_HP_bcsewpn",\
"rri_weapon_DC15C_GL_bcsewpn",\
"rri_weapon_DC15C_HP_GL_bcsewpn",\
"rri_weapon_DC19C_bcsewpn"

#define UNIT_LIST \
"rri_weapon_DC15C_GH",\
"rri_weapon_DC15C_HP_GH",\
"rri_weapon_DC15C_GL_GH",\
"rri_weapon_DC15C_HP_GL_GH",\
"rri_weapon_DC19C_GH",\
"rri_weapon_DC15C_bcsewpn_GH",\
"rri_weapon_DC15C_HP_bcsewpn_GH",\
"rri_weapon_DC15C_GL_bcsewpn_GH",\
"rri_weapon_DC15C_HP_GL_bcsewpn_GH",\
"rri_weapon_DC19C_bcsewpn_GH"
