// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_DC15C,rri_mag_DC15C,"[SOB] DC-15C");
MACRO_GH_WEAPON(rri_weapon_DC15C_HP,rri_mag_DC15C_HP,"[SOB] DC-15C High Power");
MACRO_GH_WEAPON(rri_weapon_DC15C_GL,rri_mag_DC15C,"[SOB] DC-15C GL");
MACRO_GH_WEAPON(rri_weapon_DC15C_HP_GL,rri_mag_DC15C_HP,"[SOB] DC-15C High Power GL");
MACRO_GH_WEAPON(rri_weapon_DC19C,rri_mag_DC15C,"[SOB] DC-19C");
MACRO_GH_WEAPON(rri_weapon_DC15C_bcsewpn,rri_mag_DC15C,"[SOB] DC-15C");
MACRO_GH_WEAPON(rri_weapon_DC15C_HP_bcsewpn,rri_mag_DC15C_HP,"[SOB] DC-15C High Power");
MACRO_GH_WEAPON(rri_weapon_DC15C_GL_bcsewpn,rri_mag_DC15C,"[SOB] DC-15C GL");
MACRO_GH_WEAPON(rri_weapon_DC15C_HP_GL_bcsewpn,rri_mag_DC15C_HP,"[SOB] DC-15C High Power GL");
MACRO_GH_WEAPON(rri_weapon_DC19C_bcsewpn,rri_mag_DC15C,"[SOB] DC-19C");
