// This file is automatically generated by write_aceax_compat.py
// Do not edit this file manually!

class XtdGearModels {
	class CfgWeapons {
		class rri_weapons_dc15c_DC15C {
			label = ACEAX_LABEL_DC15C;
			author = "MokTech Industries";
			options[] = {"type", "power"};

			class type {
				changeingame = 0;
				values[] = {"GL", "Rifle"};

				class GL { label = "GL"; };
				class Rifle { label = "Rifle"; };
			};

			class power {
				changeingame = 0;
				values[] = {"HighPower", "LowPower"};

				class HighPower { label = "HighPower"; };
				class LowPower { label = "LowPower"; };
			};
		};
	};
};
