// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_Firepuncher",\
"rri_weapon_Firepuncher_bcsewpn"

#define UNIT_LIST \
"rri_weapon_Firepuncher_GH",\
"rri_weapon_Firepuncher_bcsewpn_GH"
