// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_Firepuncher,rri_mag_Firepuncher,"[SOB] Firepuncher");
MACRO_GH_WEAPON(rri_weapon_Firepuncher_bcsewpn,rri_mag_Firepuncher,"[SOB] Firepuncher");
