// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_Bowcaster_base",\
"rri_weapon_Bowcaster",\
"rri_weapons_bowcaster_Bowcaster_Scope",\
"rri_weapon_Bowcaster_bcsewpn"

#define UNIT_LIST \
"rri_weapon_Bowcaster_GH",\
"rri_weapons_bowcaster_Bowcaster_Scope_GH",\
"rri_weapon_Bowcaster_bcsewpn_GH"
