// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_Bowcaster,rri_mag_Bowcaster_base,"[SOB] Bowcaster");
MACRO_GH_ITEM(rri_weapons_bowcaster_Bowcaster_Scope,"[SOB] Bowcaster Scope");
MACRO_GH_WEAPON(rri_weapon_Bowcaster_bcsewpn,rri_mag_Bowcaster_base,"[SOB] Bowcaster");
