// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_RPS6",\
"rri_weapon_RPS6_D",\
"rri_weapon_RPS6_D_Loaded",\
"rri_weapon_RPS6_D_Used"

#define UNIT_LIST \
"rri_weapon_RPS6_GH",\
"rri_weapon_RPS6_D_GH",\
"rri_weapon_RPS6_D_Used_GH"
