// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_RPS6,rri_mag_RPS6_AT,"[SOB] RPS-6");
MACRO_GH_WEAPON(rri_weapon_RPS6_D,rri_mag_RPS6_D,"[SOB] RPS-6 (Disposable)");
MACRO_GH_WEAPON(rri_weapon_RPS6_D_Used,CBA_FakeLauncherMagazine,"[SOB] RPS-6 (Disposable, Used)");
