// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_NT_Base",\
"rri_weapon_NT",\
"rri_weapons_nt_NT_Scope",\
"rri_weapon_NT_bcsewpn"

#define UNIT_LIST \
"rri_weapon_NT_GH",\
"rri_weapons_nt_NT_Scope_GH",\
"rri_weapon_NT_bcsewpn_GH"
