// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_NT,rri_mag_NT_AP,"[SOB] NT-242");
MACRO_GH_ITEM(rri_weapons_nt_NT_Scope,"[SOB] NT Scope");
MACRO_GH_WEAPON(rri_weapon_NT_bcsewpn,rri_mag_NT_AP,"[SOB] NT-242");
