// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_s195"

#define UNIT_LIST \
"rri_weapon_boltblaster_base_GH",\
"rri_weapon_boltblaster_base_bcsewpn_GH"
