// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"mti_armoury_weapon_boltblaster_base",\
"mti_armoury_weapon_boltblaster_base_bcsewpn"

#define UNIT_LIST \
"mti_armoury_weapon_boltblaster_base_GH",\
"mti_armoury_weapon_boltblaster_base_bcsewpn_GH"
