// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(mti_armoury_weapon_boltblaster_base,mti_armoury_mag_boltblaster_buck,"[SOB] Boltblaster");
MACRO_GH_WEAPON(mti_armoury_weapon_boltblaster_base_bcsewpn,mti_armoury_mag_boltblaster_buck,"[SOB] Boltblaster");
