// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_Verpine",\
"rri_weapon_Verpine_bcsewpn",\
"rri_weapons_verpine_Verpine_Scope"

#define UNIT_LIST \
"rri_weapon_Verpine_GH",\
"rri_weapon_Verpine_bcsewpn_GH",\
"rri_weapons_verpine_Verpine_Scope_GH"
