// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_Verpine,rri_mag_Verpine_Improv,"[SOB] Verpine Shatter Rifle");
MACRO_GH_WEAPON(rri_weapon_Verpine_bcsewpn,rri_mag_Verpine_Improv,"[SOB] Verpine Shatter Rifle");
MACRO_GH_ITEM(rri_weapons_verpine_Verpine_Scope,"[SOB] Verpine Scope");
