// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \

#define UNIT_LIST \
"rri_props_crates_base",\
"rri_props_crates_double_closed",\
"rri_props_crates_double_open",\
"rri_props_crates_single_closed",\
"rri_props_crates_single_open",\
"rri_props_crates_resupply_closed",\
"rri_props_crates_resupply_open",\
"rri_props_crates_double_closed_Blue",\
"rri_props_crates_double_open_Blue",\
"rri_props_crates_single_closed_Blue",\
"rri_props_crates_single_open_Blue",\
"rri_props_crates_double_closed_Green",\
"rri_props_crates_double_open_Green",\
"rri_props_crates_single_closed_Green",\
"rri_props_crates_single_open_Green",\
"rri_props_crates_double_closed_Orange",\
"rri_props_crates_double_open_Orange",\
"rri_props_crates_single_closed_Orange",\
"rri_props_crates_single_open_Orange",\
"rri_props_crates_double_closed_Purple",\
"rri_props_crates_double_open_Purple",\
"rri_props_crates_single_closed_Purple",\
"rri_props_crates_single_open_Purple",\
"rri_props_crates_double_closed_White",\
"rri_props_crates_double_open_White",\
"rri_props_crates_single_closed_White",\
"rri_props_crates_single_open_White",\
"rri_props_crates_Fortify_Small",\
"rri_props_crates_Fortify_medium",\
"rri_props_crates_Fortify_large",\
"rri_props_crates_Droppod_closed",\
"rri_props_crates_Droppod_open",\
"rri_props_crates_fuel_canister",\
"rri_props_crates_droppod_Arc_closed",\
"rri_props_crates_droppod_Arc_open",\
"rri_props_crates_droppod_Medical_closed",\
"rri_props_crates_droppod_Medical_open",\
"rri_props_crates_droppod_Commando_closed",\
"rri_props_crates_droppod_Commando_open",\
"rri_props_crates_droppod_Trooper_closed",\
"rri_props_crates_droppod_Trooper_open"
