// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_valken38x",\
"rri_weapon_valken39y",\
"rri_weapon_valken38x_bcsewpn",\
"rri_weapon_valken39y_bcsewpn"

#define UNIT_LIST \
"rri_weapon_valken38x_GH",\
"rri_weapon_valken39y_GH",\
"rri_weapon_valken38x_bcsewpn_GH",\
"rri_weapon_valken39y_bcsewpn_GH"
