// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_valken38x,rri_mag_valken38x,"[SOB] Valken-38X");
MACRO_GH_WEAPON(rri_weapon_valken39y,rri_mag_valken39y,"[SOB] Valken-39Y");
MACRO_GH_WEAPON(rri_weapon_valken38x_bcsewpn,rri_mag_valken38x,"[SOB] Valken-38X");
MACRO_GH_WEAPON(rri_weapon_valken39y_bcsewpn,rri_mag_valken39y,"[SOB] Valken-39Y");
