// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_DLT19",\
"rri_weapon_DLT19_bcsewpn"

#define UNIT_LIST \
"rri_weapon_DLT19_GH",\
"rri_weapon_DLT19_bcsewpn_GH"
