// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_DLT19,rri_mag_DLT19,"[SOB] DLT-19X");
MACRO_GH_WEAPON(rri_weapon_DLT19_bcsewpn,rri_mag_DLT19,"[SOB] DLT-19X");
