// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_e403",\
"rri_weapon_e403_bcsewpn"

#define UNIT_LIST \
"rri_weapon_e403_GH",\
"rri_weapon_e403_bcsewpn_GH"
