// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_e403,rri_mag_e403_he,"[SOB] E403 Assault Cannon");
MACRO_GH_WEAPON(rri_weapon_e403_bcsewpn,rri_mag_e403_he,"[SOB] E403 Assault Cannon");
