// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_equipment_jumptrooper_helmet_p1_base",\
"rri_equipment_jumptrooper_helmet_p1_illum_base",\
"rri_equipment_jumptrooper_helmet_Cadet",\
"rri_equipment_jumptrooper_helmet_Trooper",\
"rri_equipment_jumptrooper_helmet_TL",\
"rri_equipment_jumptrooper_helmet_SL",\
"rri_equipment_jumptrooper_helmet_Medic",\
"rri_equipment_jumptrooper_helmet_EOD",\
"rri_equipment_jumptrooper_nvg_Visor",\
"rri_equipment_jumptrooper_nvg_Rangefinder",\
"rri_equipment_jumptrooper_uniform_base",\
"rri_equipment_jumptrooper_uniform_Cadet",\
"rri_equipment_jumptrooper_uniform_Trooper",\
"rri_equipment_jumptrooper_uniform_TL",\
"rri_equipment_jumptrooper_uniform_SL",\
"rri_equipment_jumptrooper_uniform_Medic",\
"rri_equipment_jumptrooper_uniform_EOD",\
"rri_equipment_jumptrooper_vest_base",\
"rri_equipment_jumptrooper_vest_Cadet",\
"rri_equipment_jumptrooper_vest_NCO",\
"rri_equipment_jumptrooper_vest_Medic",\
"rri_equipment_jumptrooper_vest_EOD"

#define UNIT_LIST \
"rri_equipment_jumptrooper_backpack_base",\
"rri_equipment_jumptrooper_backpack_Cadet",\
"rri_equipment_jumptrooper_backpack_TL",\
"rri_equipment_jumptrooper_backpack_SL",\
"rri_equipment_jumptrooper_backpack_Medic",\
"rri_equipment_jumptrooper_backpack_EOD",\
"rri_equipment_jumptrooper_unit_base",\
"rri_equipment_jumptrooper_unit_Cadet",\
"rri_equipment_jumptrooper_unit_Trooper",\
"rri_equipment_jumptrooper_unit_TL",\
"rri_equipment_jumptrooper_unit_SL",\
"rri_equipment_jumptrooper_unit_Medic",\
"rri_equipment_jumptrooper_unit_EOD",\
"rri_equipment_jumptrooper_helmet_Cadet_GH",\
"rri_equipment_jumptrooper_helmet_Trooper_GH",\
"rri_equipment_jumptrooper_helmet_TL_GH",\
"rri_equipment_jumptrooper_helmet_SL_GH",\
"rri_equipment_jumptrooper_helmet_Medic_GH",\
"rri_equipment_jumptrooper_helmet_EOD_GH",\
"rri_equipment_jumptrooper_nvg_Visor_GH",\
"rri_equipment_jumptrooper_nvg_Rangefinder_GH",\
"rri_equipment_jumptrooper_uniform_Cadet_GH",\
"rri_equipment_jumptrooper_uniform_Trooper_GH",\
"rri_equipment_jumptrooper_uniform_TL_GH",\
"rri_equipment_jumptrooper_uniform_SL_GH",\
"rri_equipment_jumptrooper_uniform_Medic_GH",\
"rri_equipment_jumptrooper_uniform_EOD_GH",\
"rri_equipment_jumptrooper_vest_base_GH",\
"rri_equipment_jumptrooper_vest_Cadet_GH",\
"rri_equipment_jumptrooper_vest_NCO_GH",\
"rri_equipment_jumptrooper_vest_Medic_GH",\
"rri_equipment_jumptrooper_vest_EOD_GH"
