// This file is automatically generated by write_aceax_compat.py
// Do not edit this file manually!

class XtdGearModels {
	class CfgWeapons {
		class rri_equipment_jumptrooper_helmet {
			label = ACEAX_LABEL_HELMET;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"Cadet", "EOD", "Medic", "SL", "TL", "Trooper"};

				class Cadet { label = "Cadet"; };
				class EOD { label = "EOD"; };
				class Medic { label = "Medic"; };
				class SL { label = "SL"; };
				class TL { label = "TL"; };
				class Trooper { label = "Trooper"; };
			};
		};
		class rri_equipment_jumptrooper_nvg {
			label = ACEAX_LABEL_NVG;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"MacroBinoculars", "Rangefinder"};

				class MacroBinoculars { label = "MacroBinoculars"; };
				class Rangefinder { label = "Rangefinder"; };
			};
		};
		class rri_equipment_jumptrooper_uniform {
			label = ACEAX_LABEL_UNIFORM;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"Cadet", "EOD", "Medic", "SquadLead", "Teamlead", "Trooper"};

				class Cadet { label = "Cadet"; };
				class EOD { label = "EOD"; };
				class Medic { label = "Medic"; };
				class SquadLead { label = "SquadLead"; };
				class Teamlead { label = "Teamlead"; };
				class Trooper { label = "Trooper"; };
			};
		};
		class rri_equipment_jumptrooper_vest {
			label = ACEAX_LABEL_VEST;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"Cadet", "EOD", "Medic", "NCO", "Trooper"};

				class Cadet { label = "Cadet"; };
				class EOD { label = "EOD"; };
				class Medic { label = "Medic"; };
				class NCO { label = "NCO"; };
				class Trooper { label = "Trooper"; };
			};
		};
	};
	class CfgVehicles {
		class rri_equipment_jumptrooper_jumppack {
			label = ACEAX_LABEL_JUMPPACK;
			author = "MokTech Industries";
			options[] = {"camo"};

			class camo {
				changeingame = 0;
				values[] = {"Base", "Cadet", "EOD", "Medic", "SL", "TL"};

				class Base { label = "Base"; };
				class Cadet { label = "Cadet"; };
				class EOD { label = "EOD"; };
				class Medic { label = "Medic"; };
				class SL { label = "SL"; };
				class TL { label = "TL"; };
			};
		};
	};
};
