// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"mti_armoury_props_misc_spike_item",\
"mti_armoury_props_misc_lockpick_item",\
"mti_armoury_props_misc_clacker_item",\
"mti_armoury_props_misc_toolkit_item"

#define UNIT_LIST \
"mti_armoury_props_misc_shark_fren",\
"mti_armoury_props_misc_barricade",\
"mti_armoury_props_misc_toolbox",\
"mti_armoury_props_misc_clacker",\
"mti_armoury_props_misc_lockpick",\
"mti_armoury_props_misc_charity_wall",\
"mti_armoury_props_misc_spike_item_GH",\
"mti_armoury_props_misc_lockpick_item_GH",\
"mti_armoury_props_misc_clacker_item_GH",\
"mti_armoury_props_misc_toolkit_item_GH"
