// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_props_misc_spike_item",\
"rri_props_misc_lockpick_item",\
"rri_props_misc_clacker_item",\
"rri_props_misc_toolkit_item"

#define UNIT_LIST \
"rri_props_misc_barricade",\
"rri_props_misc_toolbox",\
"rri_props_misc_clacker",\
"rri_props_misc_lockpick",\
"rri_props_misc_charity_wall",\
"rri_props_misc_spike_item_GH",\
"rri_props_misc_lockpick_item_GH",\
"rri_props_misc_clacker_item_GH",\
"rri_props_misc_toolkit_item_GH"
