// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_ITEM(mti_armoury_props_misc_spike_item,"[SOB] Computer Spike");
MACRO_GH_ITEM(mti_armoury_props_misc_lockpick_item,"[SOB] ALCD-1233 Lockpick");
MACRO_GH_ITEM(mti_armoury_props_misc_clacker_item,"[SOB] Advanced Firing Device");
MACRO_GH_ITEM(mti_armoury_props_misc_toolkit_item,"[SOB] Toolkit");
