// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_cyclone_base",\
"rri_weapon_cyclone",\
"rri_weapons_cyclone_cyclone_scope",\
"rri_weapons_cyclone_cyclone_bypod",\
"rri_weapon_cyclone_bcsewpn"

#define UNIT_LIST \
"rri_weapon_cyclone_GH",\
"rri_weapons_cyclone_cyclone_scope_GH",\
"rri_weapons_cyclone_cyclone_bypod_GH",\
"rri_weapon_cyclone_bcsewpn_GH"
