// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_cyclone,200Rnd_65x39_cased_Box,"[SOB] Cyclone Repeater");
MACRO_GH_ITEM(rri_weapons_cyclone_cyclone_scope,"[SOB] Cyclone Scope");
MACRO_GH_ITEM(rri_weapons_cyclone_cyclone_bypod,"[SOB] Cyclone Bipod");
MACRO_GH_WEAPON(rri_weapon_cyclone_bcsewpn,200Rnd_65x39_cased_Box,"[SOB] Cyclone Repeater");
