// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_acpa",\
"rri_weapon_acpa_bcsewpn"

#define UNIT_LIST \
"rri_weapon_acpa_GH",\
"rri_weapon_acpa_bcsewpn_GH"
