// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_acpa,rri_mag_ACPA_Slug,"[SOB] ACP-Array Scatter Gun");
MACRO_GH_WEAPON(rri_weapon_acpa_bcsewpn,rri_mag_ACPA_Slug,"[SOB] ACP-Array Scatter Gun");
