// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_ITEM(mti_armoury_props_medical_Injector_item_Batrox,"[SOB] Batroxobine");
MACRO_GH_ITEM(mti_armoury_props_medical_Injector_item_deraformine,"[SOB] Deraformine");
MACRO_GH_ITEM(mti_armoury_props_medical_Injector_item_latheniol,"[SOB] Latheniol");
MACRO_GH_ITEM(mti_armoury_props_medical_Injector_item_pba,"[SOB] Pentabenzadrenolyne (PBA)");
MACRO_GH_ITEM(mti_armoury_props_medical_Injector_item_Symoxin,"[SOB] Symoxin");
MACRO_GH_ITEM(mti_armoury_props_medical_Injector_item_Vutalamine,"[SOB] Vutalamine");
MACRO_GH_ITEM(mti_armoury_props_medical_Injector_item_Nevastrin8,"[SOB] Nevastrin-8");
MACRO_GH_ITEM(mti_armoury_props_medical_Injector_item_Glitteryl,"[SOB] Glitteryl");
MACRO_GH_ITEM(mti_armoury_props_medical_Injector_item_Epinephrine,"[SOB] Epinephrine");
MACRO_GH_ITEM(mti_armoury_props_medical_Injector_item_Morphine,"[SOB] Morphine");
MACRO_GH_ITEM(mti_armoury_props_medical_Bacta_Item_250,"[SOB] 250ml Bacta Tank");
MACRO_GH_ITEM(mti_armoury_props_medical_Bacta_Item_500,"[SOB] 500ml Bacta Tank");
MACRO_GH_ITEM(mti_armoury_props_medical_Bacta_Item_1000,"[SOB] 1000ml Bacta Tank");
MACRO_GH_ITEM(mti_armoury_props_medical_Bacta_spray_Item_Base,"[SOB] Bacta Spray");
MACRO_GH_ITEM(mti_armoury_props_medical_inhaler_item_Base,"[SOB] Anti-Chemical Inhaler");
MACRO_GH_ITEM(mti_armoury_props_medical_bacta_patch_item_Base,"[SOB] Bacta Patch");
MACRO_GH_ITEM(mti_armoury_props_medical_medi_sensor_item_Base,"[SOB] RFX/K Medisensor");
