// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \

#define UNIT_LIST \
"rri_props_Console_console1",\
"rri_props_Console_console2"
