// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_fc36_base",\
"rri_weapons_fc36_fc36_scope",\
"rri_weapon_fc36_base_bcsewpn"

#define UNIT_LIST \
"rri_weapon_fc36_base_GH",\
"rri_weapons_fc36_fc36_scope_GH",\
"rri_weapon_fc36_base_bcsewpn_GH"
