// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_fc36_base,rri_mag_fc36,"[SOB] FC-36");
MACRO_GH_ITEM(rri_weapons_fc36_fc36_scope,"[SOB] fc36 Scope");
MACRO_GH_WEAPON(rri_weapon_fc36_base_bcsewpn,rri_mag_fc36,"[SOB] FC-36");
