// This file is automatically generated by write_config_lists.py
// Do not edit this file manually!

#define ITEM_LIST \
"rri_weapon_dp24",\
"rri_weapon_dp24_GL",\
"rri_weapon_dp24_bcsewpn",\
"rri_weapon_dp24_GL_bcsewpn"

#define UNIT_LIST \
"rri_weapon_dp24_GH",\
"rri_weapon_dp24_GL_GH",\
"rri_weapon_dp24_bcsewpn_GH",\
"rri_weapon_dp24_GL_bcsewpn_GH"
