// This file is automatically generated by write_ground_holders.py
// Do not edit this file manually!

MACRO_GH_PREAMBLE;
MACRO_GH_WEAPON(rri_weapon_dp24,rri_mag_dp24,"[SOB] DP-24");
MACRO_GH_WEAPON(rri_weapon_dp24_GL,rri_mag_dp24,"[SOB] DP-24 GL");
MACRO_GH_WEAPON(rri_weapon_dp24_bcsewpn,rri_mag_dp24,"[SOB] DP-24");
MACRO_GH_WEAPON(rri_weapon_dp24_GL_bcsewpn,rri_mag_dp24,"[SOB] DP-24 GL");
